### PR TITLE
load photos from SD card also

### PR DESCRIPTION
**Pull request by Karry**
Fix for issue: https://github.com/mholo65/harbour-filters/issues/3

Tested on SFOS 3.0.1

### CODE REVIEW

**Comment by Karry** [comment]
Should I increment package version to `0.3.3` and send you rpm packages for Harbour? :-)

**Comment by mholo65** [comment]
@Karry thanks for this! Yes, binaries would be great!

**Comment by mholo65** [comment]
You could increment to 0.4.0 since this release contains new features. Also, update version in About page. See https://github.com/mholo65/harbour-filters/commit/02c460e6c29354b694ab2604984744c57c61a105

**Review by bjorkstromm — APPROVED** [review]
LGTM :+1:

**Comment by bjorkstromm** [comment]
@Karry, thank you for your contribution! Your changes have been merged!

**Comment by Karry** [comment]
You are welcome. Here are rpm packages, if you don't have installed SDK now: https://cloud.karry.cz/index.php/s/KiTOOD9xZpw4Sbz

**Comment by bjorkstromm** [comment]
Submitted to Harbour! I'll let you know how it goes!

**Comment by bjorkstromm** [comment]
@Karry package got approved by QA and should probably be visible in store soon.

**Comment by Karry** [comment]
Great to read that :-) Thank you!

**Pull request merged**
